---
- hosts: test
  tasks:
  - name: Check the server reachablity
    ping:
    register: ping_out
    
  - shell: whoami
    register: out
    become: yes
    become_method: sudo
   
  - debug: var=out
    
